name: deploy-shiny

on:
  push:
    branches: [main, master]
    paths-ignore: 
      - '**/README.md'
      - 'doc/**'
      
  pull_request:
    branches: [main, master]
    paths-ignore: 
      - '**/README.md'
      - 'doc/**'

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup system dependencies
        run: |
          packages=(
            libcurl4-openssl-dev
            libgdal-dev
            libproj-dev
            libudunits2-dev
          )
          sudo apt-get update
          sudo apt-get install --yes "${packages[@]}"

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 4.3

          
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      - name: Install required R packages
        run: |
          install.packages(c(
            "treesitter",
            "treesitter.r",
            "shiny", 
            "shinyWidgets", 
            "bs4Dash", 
            "htmltools", 
            "DBI", 
            "glue",
            "box.lsp",
            "rhino",
            "RSQLite",
            "dplyr"
          ), repos = "https://cloud.r-project.org")
          
        shell: Rscript {0}
        
      - name: Build Sass
        if: always()
        shell: Rscript {0}
        run: rhino::build_sass()
        
      - name: Push to shinyapps.io
        if: github.event_name == 'push'
        run: |
          install.packages("rsconnect", repos="http://cran.us.r-project.org")
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'Stint', forceUpdate = TRUE)
        shell: Rscript {0}
