name: deploy-shiny

on:
  push:
    branches: [main, master]
    paths-ignore: '**/README.md'
  pull_request:
    branches: [main, master]
    paths-ignore: '**/README.md'

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libcurl4-openssl-dev \
            libxml2-dev \
            libssl-dev \
            libgdal-dev \
            libproj-dev \
            libudunits2-dev \
            libharfbuzz-dev \
            libfribidi-dev

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv
      
      - name: Install missing package box.lsp
        run: |
          Rscript -e "if(!requireNamespace('box.lsp')) install.packages('box.lsp', repos = 'https://cloud.r-project.org')"


      - name: Bootstrap renv
        run: |
          Rscript -e "if(!requireNamespace('renv')) install.packages('renv', repos = 'https://cloud.r-project.org')"
          echo "RENV_PATHS_ROOT=${{ github.workspace }}/.renv" >> $GITHUB_ENV

      - name: Restore packages
        run: |
          Rscript -e "renv::restore(confirm = FALSE, clean = TRUE)"

      - name: Push to shinyapps.io
        if: github.event_name == 'push'
        run: |
          install.packages("rsconnect", repos="http://cran.us.r-project.org")
          rsconnect::setAccountInfo(name="${{secrets.SHINY_ACC_NAME}}", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")
          rsconnect::deployApp(appName = 'ZooShopInsights', forceUpdate = TRUE)
        shell: Rscript {0}
